# -*- mode: ruby -*-
# vi: set ft=ruby :
AWS_ACCESS_KEY_ID = ENV['AWS_ACCESS_KEY_ID']
AWS_ACCESS_KEY = ENV['AWS_ACCESS_KEY']
AWS_PK_PATH = ENV['AWS_PK_PATH']
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "windows" do |windows|
    windows.vm.box = "dummy"
    windows.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    windows.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY

      #this pre-baked AMI, not pure base image
      aws.ami = "ami-c9e923be"
      aws.region = "eu-west-1"
      aws.instance_type = "m3.medium"

      aws.keypair_name = "windows_agent_packager"
      override.ssh.username = "Administrator"
      override.ssh.private_key_path = AWS_PK_PATH

      aws.tags = {
          "Name" => "windows agent packager",
      }
      aws.security_groups = "vagrant_windows"
    end

    windows.vm.synced_folder ".", "/vagrant", disabled: true
    windows.vm.synced_folder ".", "/home/vagrant"

    #shell provision use bash, so use cmd to run batch script
    windows.vm.provision "shell" do |shell|
      shell.inline = 'cmd /c "c:\\cygwin64\\home\\vagrant\\provision.bat"'
      shell.privileged = false
    end  
  end
end
