########
# Copyright (c) 2014 GigaSpaces Technologies Ltd. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
#    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    * See the License for the specific language governing permissions and
#    * limitations under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|

  config.vm.define "centos" do |centos|
    #dummy box, will be overriden
    centos.vm.box = "dummy"
    centos.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    centos.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY

      aws.ami = "ami-3689325f"
      aws.region = "eu-west-1"
      aws.instance_type = "m3.medium"

      aws.keypair_name = "vagrant_build"
      override.ssh.username = "centos"
      override.ssh.private_key_path = "~/.ssh/aws/vagrant_build.pem"

      aws.tags = {
          "Name" => "vagrant components centos build",
      }
        aws.security_groups = "vagrant_core_build"
    end

    #need to sync folders
    centos.vm.synced_folder "../", "/home/vagrant/cloudify-packager", create: true

    centos.vm.provision "shell" do |shell|
      shell.path = "provision.sh"
      shell.privileged = true
    end

  end

end
