#!/bin/bash

printf "deleting events index if exists...\n" && \
curl --silent --retry 5 --retry-delay 3 -XDELETE http://localhost:9200/cloudify_events/ && \
printf "creating events index...\n" && \
curl --fail --silent --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_events -d '{"settings": {"analysis": {"analyzer": {"default": {"tokenizer": "whitespace"}}}}}' && \
printf "deleting index if exists...\n" && \
curl --silent --silent --retry 5 --retry-delay 3 -XDELETE http://localhost:9200/cloudify_storage && \
printf "creating index...\n" && \
curl --fail --silent --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage -d '{"settings": {"analysis": {"analyzer": {"default": {"tokenizer": "whitespace"}}}}}' && \
printf "creating blueprint mapping...\n" && \
curl --fail --silent --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage/blueprint/_mapping -d '{"blueprint": {"properties": {"plan": {"enabled": false}}}}' && \
printf "creating deployment mapping...\n" && \
curl --fail --silent --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage/deployment/_mapping -d '{"deployment": {"properties": {"workflows": {"enabled": false}, "inputs": {"enabled": false}, "policy_type": {"enabled": false}, "policy_triggers": {"enabled": false}, "groups": {"enabled": false}, "outputs": {"enabled": false}}}}' && \
printf "creating node mapping...\n" && \
curl --fail --silent --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage/node/_mapping -d '{ "node": { "_id": { "path": "id" }, "properties": { "types": { "type": "string", "index_name": "type" }, "properties": { "enabled": false }, "operations": { "enabled": false } } } }' && \
printf "creating node-instance mapping...\n" && \
curl --fail --silent --retry 5 --retry-delay 3 -XPUT http://localhost:9200/cloudify_storage/node_instance/_mapping -d '{ "node_instance": { "_id": { "path": "id" }, "properties": { "runtime_properties": { "enabled": false } } } }' && \
printf "printing mappings...\n" && \
curl --fail --silent --retry 5 --retry-delay 3 -XGET http://localhost:9200/cloudify_storage/_mapping?pretty=1