########
# Copyright (c) 2014 GigaSpaces Technologies Ltd. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
#    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    * See the License for the specific language governing permissions and
#    * limitations under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :

BASE_BOX_NAME = 'hashicorp/precise64'

Vagrant.configure('2') do |config|

  config.vm.define :packman do |packman|
    packman.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024']
    end
    packman.vm.box = BASE_BOX_NAME
    packman.vm.hostname = 'packman'
    packman.vm.synced_folder "../", "/home/vagrant/cloudify-packager", create: true
    packman.vm.provision "shell", path: "provision.sh", privileged: true
  end

end
