########
# Copyright (c) 2014 GigaSpaces Technologies Ltd. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
#    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    * See the License for the specific language governing permissions and
#    * limitations under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :



BASE_BOX_NAME = 'precise64'
BASE_BOX_URI = 'http://files.vagrantup.com/precise64.box'

Vagrant.configure('2') do |config|

  config.vm.define :packman do |packman|

    packman_ip = '10.0.0.2'

    packman.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024']
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    packman.vm.box = BASE_BOX_NAME
    packman.vm.box_url = BASE_BOX_URI
    packman.vm.network :private_network, ip: packman_ip
    packman.vm.hostname = 'packman'
    packman.vm.synced_folder "../", "/home/vagrant/cloudify-packager", create: true
    packman.vm.provision "shell", path: "provision.sh", privileged: true
  end

  config.vm.define :tester do |tester|

    tester_ip = '10.0.0.10'

    tester.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '2048']
    end
    tester.vm.box = BASE_BOX_NAME
    tester.vm.box_url = BASE_BOX_URI
    tester.vm.network :private_network, ip: tester_ip
    tester.vm.hostname = 'tester'
    tester.vm.synced_folder "../", "/home/vagrant/cloudify-packager", create: true
    command = "
      echo bootstrapping... &&

      # update - (optional) if you want to install additional packages on the testing server.
      # sudo apt-get -y update &&

      # install prereqs
      # sudo apt-get install -y vim

      echo bootstrap done
      "

    tester.vm.provision :shell, :inline => command
  end

end
