########
# Copyright (c) 2014 GigaSpaces Technologies Ltd. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
#    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    * See the License for the specific language governing permissions and
#    * limitations under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :

AWS_ACCESS_KEY_ID = ENV['AWS_ACCESS_KEY_ID']
AWS_ACCESS_KEY = ENV['AWS_ACCESS_KEY']

UBUNTU_TRUSTY_BOX_NAME = 'ubuntu/trusty64'
UBUNTU_PRECISE_BOX_NAME = 'hashicorp/precise64'
DEBIAN_JESSIE_BOX_NAME = 'binarydata/debian-jessie'
CENTOS_FINAL_BOX_NAME = 'chef/centos-6.5'

Vagrant.configure('2') do |config|
  config.vm.define "debian_jessie_aws" do |debian_jessie|
    # dummy box, will be overriden
    config.nfs.functional = false
    debian_jessie.vm.box = "dummy"
    debian_jessie.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    debian_jessie.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY

      # debian-jessie 64bit box
      aws.ami = "ami-699f021e"
      aws.region = "eu-west-1"
      aws.instance_type = "m3.medium"

      aws.keypair_name = "vagrant_build"
      override.ssh.username = "admin"
      override.ssh.private_key_path = "/home/.ssh/aws/vagrant_build.pem"

      aws.tags = {
          "Name" => "vagrant debian jessie agent build",
      }
        aws.security_groups = "vagrant_cfy_build"
    end

    # need to sync folders
    debian_jessie.vm.synced_folder "../../", "/cloudify-packager", create: true, type: "rsync",
    rsync__exclude: ".git/",
    rsync__args: ["--verbose", "--rsync-path='sudo rsync'"]
    debian_jessie.vm.provision "shell" do |s|
      s.path = "provision.sh"
      s.args = "debian-jessie"
      s.privileged = false
    end
  end
  config.vm.define "ubuntu_trusty_aws" do |ubuntu_trusty|
    # dummy box, will be overriden
    ubuntu_trusty.vm.box = "dummy"
    ubuntu_trusty.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    ubuntu_trusty.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY

      # official ubuntu 14.04 64bit box
      aws.ami = "ami-f0b11187"
      aws.region = "eu-west-1"
      aws.instance_type = "m3.medium"

      aws.keypair_name = "vagrant_build"
      override.ssh.username = "ubuntu"
      override.ssh.private_key_path = "/home/.ssh/aws/vagrant_build.pem"

      aws.tags = {
          "Name" => "vagrant ubuntu trusty agent build",
      }
        aws.security_groups = "vagrant_cfy_build"
    end

    # need to sync folders
    ubuntu_trusty.vm.synced_folder "../../", "/cloudify-packager", create: true
    ubuntu_trusty.vm.provision "shell" do |s|
      s.path = "provision.sh"
      s.args = "Ubuntu-trusty"
      s.privileged = false
    end
  end
  config.vm.define "ubuntu_precise_aws" do |ubuntu_precise|
    # dummy box, will be overriden
    ubuntu_precise.vm.box = "dummy"
    ubuntu_precise.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    ubuntu_precise.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY

      # official ubuntu 12.04 64bit box
      aws.ami = "ami-036eaa74"
      aws.region = "eu-west-1"
      aws.instance_type = "m3.medium"

      aws.keypair_name = "vagrant_build"
      override.ssh.username = "ubuntu"
      override.ssh.private_key_path = "/home/.ssh/aws/vagrant_build.pem"

      aws.tags = {
          "Name" => "vagrant ubuntu precise agent build",
      }
        aws.security_groups = "vagrant_cfy_build"
    end

    # need to sync folders
    ubuntu_precise.vm.synced_folder "../../", "/cloudify-packager", create: true
    ubuntu_precise.vm.provision "shell" do |s|
      s.path = "provision.sh"
      s.args = "Ubuntu-precise"
      s.privileged = false
    end
  end
  config.vm.define "centos_final_aws" do |centos_final|
    #dummy box, will be overriden
    centos_final.vm.box = "dummy"
    centos_final.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    centos_final.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY

      # unofficial centos6.4 64bit box
      aws.ami = "ami-3b39ee4c"
      aws.region = "eu-west-1"
      aws.instance_type = "m3.medium"

      aws.keypair_name = "vagrant_build"
      override.ssh.username = "root"
      override.ssh.private_key_path = "/home/.ssh/aws/vagrant_centos_build.pem"

      aws.tags = {
          "Name" => "vagrant agent centos build",
      }
        aws.security_groups = "vagrant_linux_build"
    end

    #need to sync folders
    centos_final.vm.synced_folder "../../", "/cloudify-packager", create: true, type: "rsync", rsync__exclude: ".git/"
    centos_final.vm.provision "shell" do |s|
      s.path = "provision.sh"
      s.args = "centos-Final"
      s.privileged = false
    end
  end
  config.vm.define "windows_aws" do |windows|
    windows.vm.box = "dummy"
    windows.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    windows.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY

      # this a pre-baked AMI, not pure base image
      aws.ami = "ami-bbd90ecc"
      aws.region = "eu-west-1"
      aws.instance_type = "m3.medium"

      aws.keypair_name = "windows_agent_packager"
      override.ssh.username = "Administrator"
      override.ssh.private_key_path = AWS_PK_PATH

      aws.tags = {
          "Name" => "windows agent packager",
      }
      aws.security_groups = "vagrant_windows"
    end

    windows.vm.synced_folder ".", "/vagrant", disabled: true
    windows.vm.synced_folder ".", "/home/vagrant"

    # shell provisioning uses bash, so use cmd to run batch script
    windows.vm.provision "shell" do |shell|
      shell.inline = 'cmd /c "c:\\cygwin64\\home\\vagrant\\provision.bat"'
      shell.privileged = false
    end
  end


  config.vm.define :debian_jessie do |local|
    local.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024']
    end
    local.vm.box = DEBIAN_JESSIE_BOX_NAME
    local.vm.hostname = 'local'
    local.vm.synced_folder "../../", "/cloudify-packager", create: true
    local.vm.provision "shell" do |s|
      s.path = "provision.sh"
      s.args = "debian-jessie"
      s.privileged = false
    end
  end
  config.vm.define :ubuntu_precise do |local|
    local.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024']
    end
    local.vm.box = UBUNTU_PRECISE_BOX_NAME
    local.vm.hostname = 'local'
    local.vm.synced_folder "../../", "/cloudify-packager", create: true
    local.vm.provision "shell" do |s|
      s.path = "provision.sh"
      s.args = "Ubuntu-precise"
      s.privileged = false
    end
  end
  config.vm.define :ubuntu_trusty do |local|
    local.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024']
    end
    local.vm.box = UBUNTU_TRUSTY_BOX_NAME
    local.vm.hostname = 'local'
    local.vm.synced_folder "../../", "/cloudify-packager", create: true
    local.vm.provision "shell" do |s|
      s.path = "provision.sh"
      s.args = "Ubuntu-trusty"
      s.privileged = false
    end
  end
  config.vm.define :centos_final_cli do |local|
    local.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024']
    end
    local.vm.box = CENTOS_FINAL_BOX_NAME
    local.vm.hostname = 'local'
    local.vm.synced_folder "../../", "/cloudify-packager", create: true
    local.vm.provision "shell" do |s|
      s.path = "provision.sh"
      s.privileged = false
    end
  end
end