########
# Copyright (c) 2014 GigaSpaces Technologies Ltd. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
#    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    * See the License for the specific language governing permissions and
#    * limitations under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :

AWS_ACCESS_KEY_ID = ENV['AWS_ACCESS_KEY_ID']
AWS_ACCESS_KEY = ENV['AWS_ACCESS_KEY']


Vagrant.configure('2') do |config|

  # AWS VM'S
  config.vm.define :ubuntu_trusty do |ubuntu_trusty|
    #dummy box, will be overriden
    ubuntu_trusty.vm.box = "dummy"
    ubuntu_trusty.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    # vagrant up ubuntu --provider=aws
    ubuntu_trusty.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY

      #official ubuntu 14.04 64bit box
      aws.ami = "ami-f0b11187"
      aws.region = "eu-west-1"
      aws.instance_type = "m3.medium"

      aws.keypair_name = "vagrant_build"
      override.ssh.username = "ubuntu"
      override.ssh.private_key_path = "~/.ssh/aws/vagrant_build.pem"

      aws.tags = {
          "Name" => "vagrant agent ubuntu trusty build",
      }
        aws.security_groups = "vagrant_cfy_build"
    end

    # need to sync folders
    ubuntu_trusty.vm.synced_folder "../../", "/cloudify-packager", create: true
    ubuntu_trusty.vm.provision "shell", path: "provision.sh", privileged: false
  end

  config.vm.define :ubuntu_precise do |ubuntu_precise|
    # dummy box, will be overriden
    ubuntu_precise.vm.box = "dummy"
    ubuntu_precise.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    # vagrant up ubuntu --provider=aws
    ubuntu_precise.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY

      # official ubuntu 12.04 64bit box
      aws.ami = "ami-036eaa74"
      aws.region = "eu-west-1"
      aws.instance_type = "m3.medium"

      aws.keypair_name = "vagrant_build"
      override.ssh.username = "ubuntu"
      override.ssh.private_key_path = "~/.ssh/aws/vagrant_build.pem"

      aws.tags = {
          "Name" => "vagrant agent ubuntu precise build",
      }
        aws.security_groups = "vagrant_cfy_build"
    end

    # need to sync folders
    ubuntu_precise.vm.synced_folder "../../", "/cloudify-packager", create: true
    ubuntu_precise.vm.provision "shell", path: "provision.sh", privileged: false
  end

  config.vm.define :centos_64 do |centos_64|
    # dummy box, will be overriden
    centos_64.vm.box = "dummy"
    centos_64.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    # vagrant up centos_64 --provider=aws
    centos_64.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY

      # unofficial centos6.4 64bit box
      aws.ami = "ami-3b39ee4c"
      aws.region = "eu-west-1"
      aws.instance_type = "m3.medium"

      aws.keypair_name = "vagrant_build"
      override.ssh.username = "root"
      override.ssh.private_key_path = "~/.ssh/aws/vagrant_build.pem"

      aws.tags = {
          "Name" => "vagrant agent centos build",
      }
        aws.security_groups = "vagrant_linux_build"
    end

    #need to sync folders
    centos_64.vm.synced_folder "../../", "/cloudify-packager", create: true
    centos_64.vm.provision "shell", path: "provision.sh", privileged: false
  end


  # VIRTUALBOX VM'S
  config.vm.define :local_ubuntu_trusty do |local_ubuntu_trusty|
    local_ubuntu_trusty.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024']
    end
    local_ubuntu_trusty.vm.box = 'ubuntu/trusty64'
    local_ubuntu_trusty.vm.synced_folder "../../", "/cloudify-packager", create: true
    local_ubuntu_trusty.vm.provision "shell", path: "provision.sh", privileged: false
  end

  config.vm.define :local_ubuntu_precise do |local_ubuntu_precise|
    local_ubuntu_precise.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024']
    end
    local_ubuntu_precise.vm.box = 'hashicorp/precise64'
    local_ubuntu_precise.vm.synced_folder "../../", "/cloudify-packager", create: true
    local_ubuntu_precise.vm.provision "shell", path: "provision.sh", privileged: false
  end

  config.vm.define :local_centos_64 do |local_centos_64|
    local_centos_64.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024']
    end
    local_centos_64.vm.box = 'centos6point4'
    local_centos_64.vm.box_url = 'https://github.com/2creatives/vagrant-centos/releases/download/v0.1.0/centos64-x86_64-20131030.box'
    local_centos_64.vm.synced_folder "../../", "/cloudify-packager", create: true
    local_centos_64.vm.provision "shell", path: "provision.sh", privileged: false
  end
end
