#!/bin/sh
generate_and_build()
{
    SERVICE=$1
    sudo jocker -t ${SERVICE}/${SERVICE}.Dockerfile.template -o Dockerfile -f vars.py
    sudo docker build -t cloudify/${SERVICE} .
}

if [ "$1" == "all" ]; then
    generate_and_build nginx
    generate_and_build ui
    generate_and_build influxdb
    generate_and_build elasticsearch
    generate_and_build logstash
    generate_and_build mgmtworker
    generate_and_build rabbitmq
    generate_and_build riemann
    generate_and_build restservice
else
    generate_and_build $1
fi