#!/bin/sh
daemonize()
{
    SERVICE=$1
    sudo docker run -d --name ${SERVICE} -t cloudify/${SERVICE} /sbin/my_init
}


if [ "$1" == "all" ]; then
    daemonize nginx
    daemonize ui
    daemonize influxdb
    daemonize elasticsearch
    daemonize logstash
    daemonize mgmtworker
    daemonize rabbitmq
    daemonize riemann
    daemonize restservice
else
    daemonize $1
if