FROM {{ image.repository }}:{{ image.tag }}
MAINTAINER {{ maintainer.name }}, {{ maintainer.email }}
# ------------------------------------------------------------------------------------------------------------------------------------------ #
# INSTALL - BASE
# ------------------------------------------------------------------------------------------------------------------------------------------ #
# add utility functions
COPY utils/ /opt/tmp/utils/
COPY NOTICE.txt /root/NOTICE.txt
# Used by 'cfy status' impl to determine if running in container.
ENV DOCKER_ENV True

# ------------------------------------------------------------------------------------------------------------------------------------------ #
# INSTALL - LOGSTASH
# ------------------------------------------------------------------------------------------------------------------------------------------ #
##### ENV #####
ENV LOGSTASH_SERVICE_NAME {{ logstash.service_name }}
ENV LOGSTASH_SERVICE_DIR /etc/service/$LOGSTASH_SERVICE_NAME
# logstash conf file
ENV LOGSTASH_CONF_FILE $LOGSTASH_SERVICE_DIR/logstash.conf
##### ENV #####
# add run scripts and configuration
COPY logstash/ $LOGSTASH_SERVICE_DIR/

RUN apt-get update && \
    # installing logstash dependencies
    apt-get install -y {% for dep in logstash.reqs %} {{ dep }}{% endfor %} && \
    # download jar file
    curl {{ logstash.package_url }} --create-dirs -o $LOGSTASH_SERVICE_DIR/logstash.jar && \

EXPOSE 9999

CMD sed -i "s|ELASTICSEARCH_ADDR|$ELASTICSEARCH_PORT_9200_TCP_ADDR|g" $LOGSTASH_CONF_FILE && \
    sed -i "s|RABBITMQ_ADDR|$RABBITMQ_PORT_5672_TCP_ADDR|g" $LOGSTASH_CONF_FILE && \
    /usr/bin/java -jar $LOGSTASH_JAR_PATH agent -f $LOGSTASH_CONF_FILE