########
# Copyright (c) 2014 GigaSpaces Technologies Ltd. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
#    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    * See the License for the specific language governing permissions and
#    * limitations under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :

AWS_ACCESS_KEY_ID = ENV['AWS_ACCESS_KEY_ID']
AWS_ACCESS_KEY = ENV['AWS_ACCESS_KEY']

UBUNTU_TRUSTY_BOX_NAME = 'ubuntu/trusty64'

Vagrant.configure('2') do |config|
  config.vm.define :ubuntu_trusty_box do |local|
    local.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024']
    end
    local.vm.box = UBUNTU_TRUSTY_BOX_NAME
    local.vm.hostname = 'local'
    local.vm.synced_folder "../../", "/cloudify-packager", create: true
    local.vm.provision "shell" do |s|
      s.path = "common.sh"
      s.privileged = false
    end
  end
end