########
# Copyright (c) 2014 GigaSpaces Technologies Ltd. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
#    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    * See the License for the specific language governing permissions and
#    * limitations under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :

AWS_ACCESS_KEY_ID = ENV['AWS_ACCESS_KEY_ID']
AWS_ACCESS_KEY = ENV['AWS_ACCESS_KEY']

Vagrant.configure('2') do |config|

  config.vm.define "ubuntu" do |ubuntu|
    #dummy box, will be overriden
    ubuntu.vm.box = "dummy"
    ubuntu.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    ubuntu.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY

      #official ubuntu 12.04 64bit box
      aws.ami = "ami-036eaa74"
      aws.region = "eu-west-1"
      aws.instance_type = "m3.xlarge"

      aws.keypair_name = "vagrant_build"
      override.ssh.username = "ubuntu"
      override.ssh.private_key_path = "~/.ssh/aws/vagrant_build.pem"

      aws.tags = {
          "Name" => "vagrant components ubuntu build",
      }
        aws.security_groups = "vagrant_cfy_build"
    end

    #need to sync folders
    ubuntu.vm.synced_folder "../../", "/cloudify-packager", create: true
    # ubuntu.vm.synced_folder ".", "/vagrant", disabled: false

    ubuntu.vm.provision "shell" do |shell|
      shell.path = "provision.sh"
      shell.privileged = false
    end

  end

end
